# Generated by Django 6.0.2 on 2026-06-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='category',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movies', 'Movies'), ('Reviews', 'Reviews'), ('Wallpapers', 'Wallpapers')], default='Anime', max_length=40),
        ),
    ]
