# Generated by Django 6.0.2 on 2026-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blogapp_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='top_anime/')),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
