# Generated by Django 6.0.2 on 2026-06-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_topmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogapp',
            name='slug',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogapp',
            name='category',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movies', 'Movies'), ('Top_Anime_Series', 'Top_Anime_Series'), ('Top_Movies', 'Top_Movies')], default='Anime', max_length=40),
        ),
        migrations.AlterField(
            model_name='topmovies',
            name='image',
            field=models.ImageField(upload_to='top_movies/'),
        ),
    ]
