# Generated by Django 6.0.2 on 2026-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogapp_slug_alter_blogapp_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
