# Generated by Django 6.0.2 on 2026-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blogapp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
